[env:esp32doit-devkit-v1]
platform      = espressif32@6.13.0
board         = esp32doit-devkit-v1
framework     = arduino
upload_speed  = 921600
monitor_speed = 115200
lib_deps      = 
    esphome/AsyncTCP-esphome@^2.0.0
    esphome/ESPAsyncWebServer-esphome@^3.0.0
    ArduinoJSON@6.19.4
board_build.partitions = storage_4MB_noota.csv